# Teoría interesante:


## Decoradores:

Sirven para añadir funcionalidades extra a cualquier función.


In [80]:
# Triquiñuelas con las funciones.

def f1():
    print('hola')


def f2(f):
    print('fex')
    f()


f1 = f2(f1)  # Esto es lo que hace un decorador.

fex
hola


In [158]:
# Un decorador es una función a la que se le pasa una función y se le asigna al nombre

# función = decorador(funcion)

def decorador(fun):
    def wrapper(*args, **kwargs):
        print('Hola soy el decorador')

        return fun(*args, **kwargs)
    return wrapper


def decoradord(fun):
    def wrapper(*args, **kwargs):
        print('Hola soy el decorador del decorador')

        return fun(*args, **kwargs)
    return wrapper


def decorador2(fun):
    @ decoradord
    def wrapper(*args, **kwargs):
        print('Hola soy el decorador2')

        return fun(*args, **kwargs)
    return wrapper


@ decorador
@ decorador2
def funcion(a, b):
    print('Hola soy una función')
    return a+b


funcion(2, 3)


# Usos: mostrar tiempo de ejecución, añadir diferencias, poner barras de carga...
# Para decorar un decorador se decora el wrapper.

Hola soy el decorador
Hola soy el decorador del decorador
Hola soy el decorador2
Hola soy una función


5

In [209]:
# Decorador para tiempo de ejecución:
def decorador(fun):
    def wrapper(*args, **kwargs):
        print('Hola soy el decorador')
        result = fun(*args, **kwargs)
        print('Tras la función')
        return result
    return wrapper


@ decorador
def funcion(a, b):
    print('Hola soy una función')
    return a+b


funcion(1, 2)

funcion.__name__

Hola soy el decorador
Hola soy una función
Tras la función


'wrapper'

Cree un decorador que de el nombre por pantalla de una función antes de ejecutarla. Luego, cree un timer (utilizando el módulo functools), que calcule el tiempo de ejecución de una función. Finalmente cree una función cualquiera y decórela con los decoradores anteriores.


In [216]:
from functools import wraps
import time

In [347]:
def nombre(fun):
    @ wraps(fun)
    def wrapper(*args, **kwargs):
        print(f'Ejecutando {fun.__name__}')
        return fun(*args, **kwargs)
    return wrapper


def timer(fun):
    @ wraps(fun)
    def wrapper(*args, **kwargs):
        inicio = time.time()
        resultado = fun(*args, **kwargs)
        fin = time.time()
        t_ejecucion = fin - inicio
        print(f'Ejecutado en {round(t_ejecucion, 3)}s')
        return resultado
    return wrapper


@ nombre
@ timer
def fun1(a, b):
    time.sleep(0.5)
    print(f'Soy {fun1.__name__} tras una dura carga de 0.5s...\n({fun1.__name__} hace como que trabaja)')
    return a + b  # para que haga algo y ver que recibe bien los argumentos


z = fun1(1, 1)

print('El resultado es: ', z)

Ejecutando fun1
Soy fun1 tras una dura carga de 0.5s...
(fun1 hace como que trabaja)
Ejecutado en 0.515s
El resultado es:  2


## Tratamiento de excepciones:

    try:
        intentamos hacer esto
    except:
        si no funciona haz esto


In [755]:
a = 2

try:
    # raise Exception    # asi forzamos una excepción
    for i in range(a):
        a = a
    print('Try')

except Exception as cosa:
    print(cosa)  # Así podemos mostrar el error que ha saltado
    print('Except')
else:  # si no saltan excepciones en el try que haga esto
    print('Else')

finally:  # siempre se ejecuta tras el try except
    print('Terminado')

Try
Else
Terminado


un try except con el finaly y el else y forzar que pasen cosas


# Numpy:


In [756]:
import numpy as np

In [974]:
arr = np.array([[1, 0, 0],
                [0, 1, 0],
                [0, 0, 1]])

print(arr.shape)

zeros = np.zeros((2, 2))
print(zeros, '\n')
a = np.random.random((3, 3, 3))
print(np.random.random((3, 3, 3)), '\n')

print(a.shape)

(3, 3)
[[0. 0.]
 [0. 0.]] 

[[[5.29860852e-01 7.61337964e-01 2.31359241e-01]
  [9.82141183e-01 4.53661913e-01 2.40635479e-01]
  [6.58933269e-01 2.14501044e-01 5.00231223e-01]]

 [[6.22279336e-01 1.38903148e-01 2.28867847e-01]
  [8.82904019e-01 5.94348072e-01 4.29509574e-01]
  [7.52215709e-01 6.72675583e-01 4.37185700e-01]]

 [[4.90888966e-01 4.72777589e-01 2.94630323e-01]
  [6.22890529e-01 1.22190616e-01 3.79013616e-01]
  [6.13037016e-01 1.93820246e-04 5.00761817e-01]]] 

(3, 3, 3)


In [1124]:
v = np.array(range(25))
v.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

Utilizando el módulo numpy, crear un vector de 9 unos utilizando una función del módulo
Luego, convertirlo a una matriz de 3 x 3
Aparte, hacer un vector de 3 elementos aleatorios
Hacer que todos los elementos de la matriz sean negativos
multiplicar el vector y la matriz


In [1126]:
import numpy as np

In [1511]:
v = np.ones(9)
m = v.reshape(3, 3)

u = np.random.random(3)

mneg = -1 * np.abs(m)

prod = u @ mneg 

prod2 = u * mneg 
print(mneg)

print('\n',prod)

print('\n',prod2)

print('\nEhque el otro producto te pilla como matriz de [v,v,v][M]:\n',[sum(prod2[0]),sum(prod2[1]),sum(prod2[2])])

print(prod2[(1,1)]) # acceder al 1,1
print(prod2[1][1]) # es lo mismo 

[[-1. -1. -1.]
 [-1. -1. -1.]
 [-1. -1. -1.]]

 [-0.58431548 -0.58431548 -0.58431548]

 [[-0.05736051 -0.47453088 -0.05242409]
 [-0.05736051 -0.47453088 -0.05242409]
 [-0.05736051 -0.47453088 -0.05242409]]

Ehque el otro producto te pilla como matriz de [v,v,v][M]:
 [-0.5843154818134975, -0.5843154818134975, -0.5843154818134975]
-0.4745308835066654
-0.4745308835066654


## Ultima parte de teoría en python