# Redes neuronales:
# Matemáticas aplicadas a la Inteligencia Artificial

## Algebra lineal:

vemos como representar un vector, como calcular su modulo, suma y resta de vectores... También gráficamente.

vemos el producto escalar y vectorial

vectores unitarios

Ahora vamos a ver matrices: 

vemos nomenclatura, vemos trasponer...

Vemos tensores:



In [3]:
import numpy as np

In [37]:
A = np.array([[1,0,0],[0,-1,1],[0,1,-1]])
B = np.array([[1,0,-1],[-1,2,-3]])

C = B @ A
D = np.kron(A,B)
print(C)
print(D)

g = np.matmul(B,A)
print(g)

[[ 1 -1  1]
 [-1 -5  5]]
[[ 1  0 -1  0  0  0  0  0  0]
 [-1  2 -3  0  0  0  0  0  0]
 [ 0  0  0 -1  0  1  1  0 -1]
 [ 0  0  0  1 -2  3 -1  2 -3]
 [ 0  0  0  1  0 -1 -1  0  1]
 [ 0  0  0 -1  2 -3  1 -2  3]]
[[ 1 -1  1]
 [-1 -5  5]]


In [32]:
print(C.shape)
print(D.shape)
tensor_gordo = np.array([D,D])

print(tensor_gordo.shape)

(2, 3)
(6, 9)
(2, 6, 9)


In [36]:
v = np.array([1,0])
u = np.array([1,1])
np.dot(u,v)

1

In [ ]:
t1 = np.array([A,B])